<a href="https://colab.research.google.com/github/Simone-Prado/Aula-Github/blob/main/Aula_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files
files.upload()

Saving clientes_credito_preparacao_ml.csv to clientes_credito_preparacao_ml (1).csv

{'clientes_credito_preparacao_ml (1).csv': b'\xef\xbb\xbfid,nome,idade,renda,divida,estado_civil,aprovado\r\n1,Ana,25,3200,1200,Solteiro,Sim\r\n2,Bruno,42,8500,2500,Casado,Sim\r\n3,Carla,31,,4200,Solteiro,N\xc3\xa3o\r\n4,Daniel,19,1800,800,solteiro,N\xc3\xa3o\r\n5,Eduarda,150,5000,1500,Casado,Sim\r\n6,Felipe,37,6200,2800,CASADO,Sim\r\n7,Gabriela,29,4100,-500,Solteiro,N\xc3\xa3o\r\n8,Henrique,48,12000,3500,Divorciado,Sim\r\n9,Isabela,34,7200,2100,Casado,Sim\r\n10,Jo\xc3\xa3o,23,2600,1800,Solteiro,N\xc3\xa3o\r\n11,Karen,51,95000,4000,Casado,Sim\r\n12,Lucas,28,3900,2400,Solteiro,N\xc3\xa3o\r\n13,Mariana,39,9000,2700,Casado,Sim\r\n14,Nicolas,33,5400,3100,Divorciado,N\xc3\xa3o\r\n15,Olivia,45,11000,1900,Casado,Sim\r\n16,Paulo,26,3000,2200,Solteiro,N\xc3\xa3o\r\n8,Henrique,48,12000,3500,Divorciado,Sim\r\n'}

In [ ]:
df = pd.read_csv("clientes_credito_preparacao_ml.csv")


df.head(17)

    id      nome  idade    renda  divida estado_civil aprovado
0    1       Ana     25   3200.0    1200     Solteiro      Sim
1    2     Bruno     42   8500.0    2500       Casado      Sim
2    3     Carla     31      NaN    4200     Solteiro      Não
3    4    Daniel     19   1800.0     800     solteiro      Não
4    5   Eduarda    150   5000.0    1500       Casado      Sim
5    6    Felipe     37   6200.0    2800       CASADO      Sim
6    7  Gabriela     29   4100.0    -500     Solteiro      Não
7    8  Henrique     48  12000.0    3500   Divorciado      Sim
8    9   Isabela     34   7200.0    2100       Casado      Sim
9   10      João     23   2600.0    1800     Solteiro      Não
10  11     Karen     51  95000.0    4000       Casado      Sim
11  12     Lucas     28   3900.0    2400     Solteiro      Não
12  13   Mariana     39   9000.0    2700       Casado      Sim
13  14   Nicolas     33   5400.0    3100   Divorciado      Não
14  15    Olivia     45  11000.0    1900       Casado      Sim
15  16     Paulo     26   3000.0    2200     Solteiro      Não
16   8  Henrique     48  12000.0    3500   Divorciado      Sim

In [ ]:
# conhecendo os dados

# quantidade de registros
# tipos das colunas
# valores faltantes
# valores minimos, maximos e categoricos

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     16 non-null     int64
 1   nome                   16 non-null     object
 2   idade                  16 non-null     int64
 3   renda                  16 non-null     float64
 4   divida                 16 non-null     float64
 5   estado_civil           16 non-null     object
 6   aprovado               16 non-null     object
 7   comprometimento_renda  16 non-null     float64
dtypes: float64(3), int64(2), object(3)
memory usage: 1.1+ KB

In [ ]:
df.describe(include="all")
#unique = nomes diferentes / top maximo(mais vezes) / frequencia / media / minimo / std desvio padrão/ 1, 2 e 3 quartil.

,id,nome,idade,renda,divida,estado_civil,aprovado
count,17.000000,17,17.000000,16.000000,17.000000,17,17
unique,NaN,16,NaN,NaN,NaN,5,2
top,NaN,Henrique,NaN,NaN,NaN,Solteiro,Sim
freq,NaN,2,NaN,NaN,NaN,6,10
mean,8.470588,NaN,41.647059,11868.750000,2335.294118,NaN,NaN
std,4.611367,NaN,29.499875,22418.852743,1195.272551,NaN,NaN
min,1.000000,NaN,19.000000,1800.000000,-500.000000,NaN,NaN
25%,5.000000,NaN,28.000000,3725.000000,1800.000000,NaN,NaN
50%,8.000000,NaN,34.000000,5800.000000,2400.000000,NaN,NaN
75%,12.000000,NaN,45.000000,9500.000000,3100.000000,NaN,NaN
max,16.000000,NaN,150.000000,95000.000000,4200.000000,NaN,NaN

In [ ]:
# dados faltantes
df.isnull().sum()

id              0
nome            0
idade           0
renda           1
divida          0
estado_civil    0
aprovado        0
dtype: int64

In [ ]:
# categorias inconsistentes
# exemplo: Casado, CASADO e casado = são todos a mesma coisa
df["estado_civil"].value_counts()

estado_civil
Solteiro      6
Casado        6
Divorciado    3
solteiro      1
CASADO        1
Name: count, dtype: int64

In [ ]:
# valores suspeitos
df[["idade","renda","divida"]].describe()

            idade         renda       divida
count   17.000000     16.000000    17.000000
mean    41.647059  11868.750000  2335.294118
std     29.499875  22418.852743  1195.272551
min     19.000000   1800.000000  -500.000000
25%     28.000000   3725.000000  1800.000000
50%     34.000000   5800.000000  2400.000000
75%     45.000000   9500.000000  3100.000000
max    150.000000  95000.000000  4200.000000

In [ ]:
# fazer uma limpeza simples

# corrigir as categorias lower=coloca as letras em minusculo
df["estado_civil"] = (df["estado_civil"].str.strip().str.lower())

df["estado_civil"].value_counts()

estado_civil
solteiro      7
casado        7
divorciado    3
Name: count, dtype: int64

In [ ]:
# Tratar a renda ausente
df["renda"] = df["renda"].fillna(df["renda"].mean())
df.head()

   id     nome  idade     renda  divida estado_civil aprovado
0   1      Ana     25   3200.00    1200     solteiro      Sim
1   2    Bruno     42   8500.00    2500       casado      Sim
2   3    Carla     31  11868.75    4200     solteiro      Não
3   4   Daniel     19   1800.00     800     solteiro      Não
4   5  Eduarda    150   5000.00    1500       casado      Sim

In [ ]:
# tratar valores invalidos
df.loc[df["idade"] > 90,"idade"] = df["idade"].mean().astype(int)
df.loc[df["divida"]< 0,"divida"] = df["divida"].mean()
df.head(10)

/tmp/ipykernel_2508/4137328938.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2335.294117647059' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df["divida"]< 0,"divida"] = df["divida"].mean()

   id      nome  idade     renda       divida estado_civil aprovado
0   1       Ana     25   3200.00  1200.000000     solteiro      Sim
1   2     Bruno     42   8500.00  2500.000000       casado      Sim
2   3     Carla     31  11868.75  4200.000000     solteiro      Não
3   4    Daniel     19   1800.00   800.000000     solteiro      Não
4   5   Eduarda     41   5000.00  1500.000000       casado      Sim
5   6    Felipe     37   6200.00  2800.000000       casado      Sim
6   7  Gabriela     29   4100.00  2335.294118     solteiro      Não
7   8  Henrique     48  12000.00  3500.000000   divorciado      Sim
8   9   Isabela     34   7200.00  2100.000000       casado      Sim
9  10      João     23   2600.00  1800.000000     solteiro      Não

In [ ]:
# remover os registros duplicados
print("Duplicados: ", df.duplicated().sum())
df = df.drop_duplicates().reset_index(drop=True)
df.head(20)

Duplicados:  1

    id      nome  idade     renda       divida estado_civil aprovado
0    1       Ana     25   3200.00  1200.000000     solteiro      Sim
1    2     Bruno     42   8500.00  2500.000000       casado      Sim
2    3     Carla     31  11868.75  4200.000000     solteiro      Não
3    4    Daniel     19   1800.00   800.000000     solteiro      Não
4    5   Eduarda     41   5000.00  1500.000000       casado      Sim
5    6    Felipe     37   6200.00  2800.000000       casado      Sim
6    7  Gabriela     29   4100.00  2335.294118     solteiro      Não
7    8  Henrique     48  12000.00  3500.000000   divorciado      Sim
8    9   Isabela     34   7200.00  2100.000000       casado      Sim
9   10      João     23   2600.00  1800.000000     solteiro      Não
10  11     Karen     51  95000.00  4000.000000       casado      Sim
11  12     Lucas     28   3900.00  2400.000000     solteiro      Não
12  13   Mariana     39   9000.00  2700.000000       casado      Sim
13  14   Nicolas     33   5400.00  3100.000000   divorciado      Não
14  15    Olivia     45  11000.00  1900.000000       casado      Sim
15  16     Paulo     26   3000.00  2200.000000     solteiro      Não

In [ ]:
# criar uma nova informação: coluna com percentual de compromentimento da renda
df["comprometimento_renda"] = df["divida"] / df["renda"]
df[["renda", "divida","comprometimento_renda","aprovado","idade"]].head(10)

      renda       divida  comprometimento_renda aprovado  idade
0   3200.00  1200.000000               0.375000      Sim     25
1   8500.00  2500.000000               0.294118      Sim     42
2  11868.75  4200.000000               0.353870      Não     31
3   1800.00   800.000000               0.444444      Não     19
4   5000.00  1500.000000               0.300000      Sim     41
5   6200.00  2800.000000               0.451613      Sim     37
6   4100.00  2335.294118               0.569584      Não     29
7  12000.00  3500.000000               0.291667      Sim     48
8   7200.00  2100.000000               0.291667      Sim     34
9   2600.00  1800.000000               0.692308      Não     23

In [ ]:
#normalização de dados: troca de letras em numeros, eliminação de colunas que não fazem sentido.
#normalização do resultado, sim = 1 / não = 0
df["aprovado"] = (
    df["aprovado"]
    .astype(str)
    .str.strip()
    .str.lower()
    .map({"sim": 1, "não": 0, "1": 1, "0": 0})
)
print(df["aprovado"].value_counts())
df[["nome", "aprovado"]].head(20)

aprovado
1    9
0    7
Name: count, dtype: int64

        nome  aprovado
0        Ana         1
1      Bruno         1
2      Carla         0
3     Daniel         0
4    Eduarda         1
5     Felipe         1
6   Gabriela         0
7   Henrique         1
8    Isabela         1
9       João         0
10     Karen         1
11     Lucas         0
12   Mariana         1
13   Nicolas         0
14    Olivia         1
15     Paulo         0

In [ ]:
# Separar as bases
# Remover os atributos irrelevantes #X são os atributos que serão usados no treinamento, o Y é o aprovado
X = df.drop(columns=["id","nome","aprovado"])

X = pd.get_dummies(X,columns=["estado_civil"], dtype=int)

y = df["aprovado"] # é o resultado (qual a informação a prever)

# print(X)

In [ ]:
# Dividir a base (os dados) 70% x 30% ou 80%(treinamento) x 20% (teste)
from sklearn.model_selection import train_test_split

X_treino, X_teste, y_treino, y_teste = train_test_split(
    X,y, test_size= 0.2, random_state=42, stratify=y
)

print("Clientes para treino: ", len(X_treino))
print("Clientes para teste: ", len(X_teste))

Clientes para treino:  12
Clientes para teste:  4

In [ ]:
#normalização
from sklearn.preprocessing import MinMaxScaler

normalizador = MinMaxScaler()
X_treino_norm = normalizador.fit_transform(X_treino)
X_teste_norm = normalizador.transform(X_teste)
pd.DataFrame(
    X_treino_norm, columns=X.columns, index=X_treino.index
)[["idade","renda","divida"]].head()

       idade     renda    divida
4   0.846154  0.317815  0.205882
8   0.576923  0.536313  0.382353
2   0.461538  1.000000  1.000000
14  1.000000  0.913718  0.323529
12  0.769231  0.715084  0.558824

In [ ]:
# Treinamento
from sklearn.linear_model import LogisticRegression

modelo = LogisticRegression(max_iter=1000)
modelo.fit(X_treino_norm, y_treino)

LogisticRegression(max_iter=1000)

In [ ]:
# Testes
y_previsto = modelo.predict(X_teste_norm)

resultado = pd.DataFrame({
    "cliente": df.loc[X_teste.index, "nome"],
    "real":y_teste.map({1:"Sim", 0:"Não"}),
    "previsto": pd.Series(y_previsto,X_teste.index).map({1: "Sim", 0: "Não"})
})
print(resultado)

     cliente real previsto
9       João  Não      Não
10     Karen  Sim      Sim
15     Paulo  Não      Não
7   Henrique  Sim      Sim